spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school-management
    username: postgres
    password: simoQB24188
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
